<?php
namespace FGC\CurrencyExchange\Setup;

use Magento\Framework\Setup\InstallDataInterface;
use Magento\Framework\Setup\ModuleContextInterface;
use Magento\Framework\Setup\ModuleDataSetupInterface;

/**
 * @codeCoverageIgnore
 */
class InstallData implements InstallDataInterface {
    /**
     * {@inheritdoc}
     * @SuppressWarnings(PHPMD.CyclomaticComplexity)
     * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
     * @SuppressWarnings(PHPMD.NPathComplexity)
     */
    public function install(ModuleDataSetupInterface $setup, ModuleContextInterface $context) {
		/**
        * Install data currency rate
        */
        $data = [
			['country_code' => 'AF', 'country_name' => 'Afghanistan', 'currency_code' => 'AFN', 'currency_name' => 'Afghani', 'rate' => 68.6245],
			['country_code' => 'AX', 'country_name' => 'Aland Islands', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'rate' => 0.85796],
			['country_code' => 'AL', 'country_name' => 'Albania', 'currency_code' => 'ALL', 'currency_name' => 'Lek', 'rate' => 114.718761],
			['country_code' => 'DZ', 'country_name' => 'Algeria', 'currency_code' => 'DZD', 'currency_name' => 'Algerian Dinar', 'rate' => 115.061],
			['country_code' => 'AS', 'country_name' => 'American Samoa', 'currency_code' => 'EUR', 'currency_name' => 'Euros', 'rate' => 0.85796],
			['country_code' => 'AD', 'country_name' => 'Andorra', 'currency_code' => 'EUR', 'currency_name' => 'Euros', 'rate' => 0.85796],
			['country_code' => 'AO', 'country_name' => 'Angola', 'currency_code' => 'AOA', 'currency_name' => 'Angolan kwanza', 'rate' => 165.9225],
			['country_code' => 'AI', 'country_name' => 'Anguilla', 'currency_code' => 'XCD', 'currency_name' => 'East Caribbean Dollar', 'rate' => 2.70255],
			['country_code' => 'AQ', 'country_name' => 'Antarctica', 'currency_code' => 'AQD', 'currency_name' => 'Antarctican dollar', 'rate' => NULL],
			['country_code' => 'AG', 'country_name' => 'Antigua and Barbuda', 'currency_code' => 'XCD', 'currency_name' => 'East Caribbean Dollar', 'rate' => 2.70255],
			['country_code' => 'AR', 'country_name' => 'Argentina', 'currency_code' => 'ARS', 'currency_name' => 'Peso', 'rate' => 17.607],
			['country_code' => 'AM', 'country_name' => 'Armenia', 'currency_code' => 'AMD', 'currency_name' => 'Dram', 'rate' => 482.586304],
			['country_code' => 'AW', 'country_name' => 'Aruba', 'currency_code' => 'ANG', 'currency_name' => 'Netherlands Antilles Guilder', 'rate' => 1.785544],
			['country_code' => 'AU', 'country_name' => 'Australian', 'currency_code' => 'AUD', 'currency_name' => 'Australian Dollars', 'rate' => 1.295308],
			['country_code' => 'AT', 'country_name' => 'Austria', 'currency_code' => 'EUR', 'currency_name' => 'Euros', 'rate' => 0.85796],
			['country_code' => 'AZ', 'country_name' => 'Azerbaijan', 'currency_code' => 'AZN', 'currency_name' => 'Manat', 'rate' => 1.6985],
			['country_code' => 'BS', 'country_name' => 'Bahamas', 'currency_code' => 'BSD', 'currency_name' => 'Bahamian Dollar', 'rate' => 1],
			['country_code' => 'BH', 'country_name' => 'Bahrain', 'currency_code' => 'BHD', 'currency_name' => 'Bahraini Dinar', 'rate' => 0.376941],
			['country_code' => 'BD', 'country_name' => 'Bangladesh', 'currency_code' => 'BDT', 'currency_name' => 'Taka', 'rate' => 83.195604],
			['country_code' => 'BB', 'country_name' => 'Barbados', 'currency_code' => 'BBD', 'currency_name' => 'Barbadian Dollar', 'rate' => 2],
			['country_code' => 'BY', 'country_name' => 'Belarus', 'currency_code' => 'BYR', 'currency_name' => 'Belarus Ruble', 'rate' => NULL],
			['country_code' => 'BE', 'country_name' => 'Belgium', 'currency_code' => 'EUR', 'currency_name' => 'Euros', 'rate' => 0.85796],
			['country_code' => 'BZ', 'country_name' => 'Belize', 'currency_code' => 'BZD', 'currency_name' => 'Belizean Dollar', 'rate' => 2.010703],
			['country_code' => 'BJ', 'country_name' => 'Benin', 'currency_code' => 'XOF', 'currency_name' => 'CFA Franc BCEAO', 'rate' => 562.785111],
			['country_code' => 'BM', 'country_name' => 'Bermuda', 'currency_code' => 'BMD', 'currency_name' => 'Bermudian Dollar', 'rate' => 1],
			['country_code' => 'BT', 'country_name' => 'Bhutan', 'currency_code' => 'INR', 'currency_name' => 'Indian Rupee', 'rate' => 64.5125],
			['country_code' => 'BO', 'country_name' => 'Bolivia', 'currency_code' => 'BOB', 'currency_name' => 'Boliviano', 'rate' => 6.927284],
			['country_code' => 'BA', 'country_name' => 'Bosnia and Herzegovina', 'currency_code' => 'BAM', 'currency_name' => 'Bosnia and Herzegovina convertible mark', 'rate' => 1.681092],
			['country_code' => 'BW', 'country_name' => 'Botswana', 'currency_code' => 'BWP', 'currency_name' => 'Pula', 'rate' => 10.557528],
			['country_code' => 'BV', 'country_name' => 'Bouvet Island', 'currency_code' => 'NOK', 'currency_name' => 'Norwegian Krone', 'rate' => 8.124565],
			['country_code' => 'BR', 'country_name' => 'Brazil', 'currency_code' => 'BRL', 'currency_name' => 'Brazil', 'rate' => 3.267524],
			['country_code' => 'IO', 'country_name' => 'British Indian Ocean Territory', 'currency_code' => 'USD', 'currency_name' => 'USD', 'rate' => 1],
			['country_code' => 'BN', 'country_name' => 'Brunei Darussalam', 'currency_code' => 'BND', 'currency_name' => 'Bruneian Dollar', 'rate' => 1.361297],
			['country_code' => 'BG', 'country_name' => 'Bulgaria', 'currency_code' => 'BGN', 'currency_name' => 'Lev', 'rate' => 1.678438],
			['country_code' => 'BF', 'country_name' => 'Burkina Faso', 'currency_code' => 'XOF', 'currency_name' => 'CFA Franc BCEAO', 'rate' => 562.785111],
			['country_code' => 'BI', 'country_name' => 'Burundi', 'currency_code' => 'BIF', 'currency_name' => 'Burundi Franc', 'rate' => 1752.45],
			['country_code' => 'KH', 'country_name' => 'Cambodia', 'currency_code' => 'KHR', 'currency_name' => 'Riel', 'rate' => 4040.35],
			['country_code' => 'CM', 'country_name' => 'Cameroon', 'currency_code' => 'XAF', 'currency_name' => 'CFA Franc BEAC', 'rate' => 562.785111],
			['country_code' => 'CA', 'country_name' => 'Canada', 'currency_code' => 'CAD', 'currency_name' => 'Canadian Dollar', 'rate' => 1.2835],
			['country_code' => 'CV', 'country_name' => 'Cape Verde', 'currency_code' => 'CVE', 'currency_name' => 'Escudo', 'rate' => 95.1],
			['country_code' => 'KY', 'country_name' => 'Cayman Islands', 'currency_code' => 'KYD', 'currency_name' => 'Caymanian Dollar', 'rate' => 0.833577],
			['country_code' => 'CF', 'country_name' => 'Central African Republic', 'currency_code' => 'XAF', 'currency_name' => 'CFA Franc BEAC', 'rate' => 562.785111],
			['country_code' => 'TD', 'country_name' => 'Chad', 'currency_code' => 'XAF', 'currency_name' => 'CFA Franc BEAC', 'rate' => 562.785111],
			['country_code' => 'CL', 'country_name' => 'Chile', 'currency_code' => 'CLP', 'currency_name' => 'Chilean Peso', 'rate' => 636.1],
			['country_code' => 'CN', 'country_name' => 'China', 'currency_code' => 'CNY', 'currency_name' => 'Yuan Renminbi', 'rate' => 6.5991],
			['country_code' => 'CX', 'country_name' => 'Christmas Island', 'currency_code' => 'AUD', 'currency_name' => 'Australian Dollars', 'rate' => 1.295308],
			['country_code' => 'CC', 'country_name' => 'Cocos (Keeling) Islands', 'currency_code' => 'AUD', 'currency_name' => 'Australian Dollars', 'rate' => 1.295308],
			['country_code' => 'CO', 'country_name' => 'Colombia', 'currency_code' => 'COP', 'currency_name' => 'Peso', 'rate' => 3065],
			['country_code' => 'KM', 'country_name' => 'Comoros', 'currency_code' => 'KMF', 'currency_name' => 'Comoran Franc', 'rate' => 423.104935],
			['country_code' => 'CD', 'country_name' => 'Congo (Kinshasa)', 'currency_code' => 'CDF', 'currency_name' => 'Congolese Frank', 'rate' => 1562.881563],
			['country_code' => 'CG', 'country_name' => 'Congo Republic of the Democratic', 'currency_code' => 'XAF', 'currency_name' => 'CFA Franc BEAC', 'rate' => 562.785111],
			['country_code' => 'CD', 'country_name' => 'Congo-Brazzaville', 'currency_code' => 'CDF', 'currency_name' => 'Congolese Frank', 'rate' => 1562.881563],
			['country_code' => 'CK', 'country_name' => 'Cook Islands', 'currency_code' => 'NZD', 'currency_name' => 'New Zealand Dollars', 'rate' => 1.444878],
			['country_code' => 'CR', 'country_name' => 'Costa Rica', 'currency_code' => 'CRC', 'currency_name' => 'Costa Rican Colon', 'rate' => 569.935],
			['country_code' => 'HR', 'country_name' => 'Croatia (Hrvatska)', 'currency_code' => 'HRK', 'currency_name' => 'Croatian Dinar', 'rate' => 6.4542],
			['country_code' => 'CU', 'country_name' => 'Cuba', 'currency_code' => 'CUP', 'currency_name' => 'Cuban Peso', 'rate' => 25.5],
			['country_code' => 'CY', 'country_name' => 'Cyprus', 'currency_code' => 'CYP', 'currency_name' => 'Cypriot Pound', 'rate' => NULL],
			['country_code' => 'CZ', 'country_name' => 'Czech Republic', 'currency_code' => 'CZK', 'currency_name' => 'Koruna', 'rate' => 21.929675],
			['country_code' => 'DK', 'country_name' => 'Denmark', 'currency_code' => 'DKK', 'currency_name' => 'Danish Krone', 'rate' => 6.384225],
			['country_code' => 'DJ', 'country_name' => 'Djibouti', 'currency_code' => 'DJF', 'currency_name' => 'Djiboutian Franc', 'rate' => 178.97],
			['country_code' => 'DM', 'country_name' => 'Dominica', 'currency_code' => 'XCD', 'currency_name' => 'East Caribbean Dollar', 'rate' => 2.70255],
			['country_code' => 'DO', 'country_name' => 'Dominican Republic', 'currency_code' => 'DOP', 'currency_name' => 'Dominican Peso', 'rate' => 47.861625],
			['country_code' => 'TP', 'country_name' => 'East Timor', 'currency_code' => 'IDR', 'currency_name' => 'Indonesian Rupiah', 'rate' => 13538.080047],
			['country_code' => 'EC', 'country_name' => 'Ecuador', 'currency_code' => 'ECS', 'currency_name' => 'Sucre', 'rate' => NULL],
			['country_code' => 'EG', 'country_name' => 'Egypt', 'currency_code' => 'EGP', 'currency_name' => 'Egyptian Pound', 'rate' => 17.6485],
			['country_code' => 'SV', 'country_name' => 'El Salvador', 'currency_code' => 'SVC', 'currency_name' => 'Salvadoran Colon', 'rate' => 8.752562],
			['country_code' => 'GQ', 'country_name' => 'Equatorial Guinea', 'currency_code' => 'XAF', 'currency_name' => 'CFA Franc BEAC', 'rate' => 562.785111],
			['country_code' => 'ER', 'country_name' => 'Eritrea', 'currency_code' => 'ETB', 'currency_name' => 'Ethiopian Birr', 'rate' => 27.286919],
			['country_code' => 'EE', 'country_name' => 'Estonia', 'currency_code' => 'EEK', 'currency_name' => 'Estonian Kroon', 'rate' => NULL],
			['country_code' => 'ET', 'country_name' => 'Ethiopia', 'currency_code' => 'ETB', 'currency_name' => 'Ethiopian Birr', 'rate' => 27.286919],
			['country_code' => 'FK', 'country_name' => 'Falkland Islands (Malvinas)', 'currency_code' => 'FKP', 'currency_name' => 'Falkland Pound', 'rate' => 0.752967],
			['country_code' => 'FO', 'country_name' => 'Faroe Islands', 'currency_code' => 'DKK', 'currency_name' => 'Danish Krone', 'rate' => 6.384225],
			['country_code' => 'FJ', 'country_name' => 'Fiji', 'currency_code' => 'FJD', 'currency_name' => 'Fijian Dollar', 'rate' => 2.074354],
			['country_code' => 'FI', 'country_name' => 'Finland', 'currency_code' => 'EUR', 'currency_name' => 'Euros', 'rate' => 0.85796],
			['country_code' => 'FR', 'country_name' => 'France', 'currency_code' => 'EUR', 'currency_name' => 'Euros', 'rate' => 0.85796],
			['country_code' => 'GF', 'country_name' => 'French Guiana', 'currency_code' => 'EUR', 'currency_name' => 'Euros', 'rate' => 0.85796],
			['country_code' => 'PF', 'country_name' => 'French Polynesia', 'currency_code' => 'XPF', 'currency_name' => 'CFP Franc', 'rate' => 102.381906],
			['country_code' => 'TF', 'country_name' => 'French Southern Territories', 'currency_code' => 'EUR', 'currency_name' => 'Euros', 'rate' => 0.85796],
			['country_code' => 'GA', 'country_name' => 'Gabon', 'currency_code' => 'XAF', 'currency_name' => 'CFA Franc BEAC', 'rate' => 562.785111],
			['country_code' => 'GM', 'country_name' => 'Gambia', 'currency_code' => 'GMD', 'currency_name' => 'Dalasi', 'rate' => 47.43],
			['country_code' => 'GE', 'country_name' => 'Georgia', 'currency_code' => 'GEL', 'currency_name' => 'Lari', 'rate' => 2.545329],
			['country_code' => 'DE', 'country_name' => 'Germany', 'currency_code' => 'EUR', 'currency_name' => 'Euros', 'rate' => 0.85796],
			['country_code' => 'GH', 'country_name' => 'Ghana', 'currency_code' => 'GHS', 'currency_name' => 'Ghana cedi', 'rate' => 4.401408],
			['country_code' => 'GI', 'country_name' => 'Gibraltar', 'currency_code' => 'GIP', 'currency_name' => 'Gibraltar Pound', 'rate' => 0.752967],
			['country_code' => 'GR', 'country_name' => 'Greece', 'currency_code' => 'EUR', 'currency_name' => 'Euros', 'rate' => 0.85796],
			['country_code' => 'GL', 'country_name' => 'Greenland', 'currency_code' => 'DKK', 'currency_name' => 'Danish Krone', 'rate' => 6.384225],
			['country_code' => 'GD', 'country_name' => 'Grenada', 'currency_code' => 'XCD', 'currency_name' => 'East Caribbean Dollar', 'rate' => 2.70255],
			['country_code' => 'GP', 'country_name' => 'Guadeloupe', 'currency_code' => 'EUR', 'currency_name' => 'Euros', 'rate' => 0.85796],
			['country_code' => 'GU', 'country_name' => 'Guam', 'currency_code' => 'USD', 'currency_name' => 'USD', 'rate' => 1],
			['country_code' => 'GT', 'country_name' => 'Guatemala', 'currency_code' => 'GTQ', 'currency_name' => 'Quetzal', 'rate' => 7.354849],
			['country_code' => 'GG', 'country_name' => 'Guernsey', 'currency_code' => 'GGP', 'currency_name' => 'Guernsey pound', 'rate' => 0.752967],
			['country_code' => 'GN', 'country_name' => 'Guinea', 'currency_code' => 'GNF', 'currency_name' => 'Guinean Franc', 'rate' => 9028.05],
			['country_code' => 'GW', 'country_name' => 'Guinea-Bissau', 'currency_code' => 'XOF', 'currency_name' => 'CFA Franc BCEAO', 'rate' => 562.785111],
			['country_code' => 'GY', 'country_name' => 'Guyana', 'currency_code' => 'GYD', 'currency_name' => 'Guyanaese Dollar', 'rate' => 207.840851],
			['country_code' => 'HT', 'country_name' => 'Haiti', 'currency_code' => 'HTG', 'currency_name' => 'Gourde', 'rate' => 63.438864],
			['country_code' => 'HM', 'country_name' => 'Heard and Mc Donald Islands', 'currency_code' => 'AUD', 'currency_name' => 'Australian Dollars', 'rate' => 1.295308],
			['country_code' => 'HN', 'country_name' => 'Honduras', 'currency_code' => 'HNL', 'currency_name' => 'Lempira', 'rate' => 23.632113],
			['country_code' => 'HK', 'country_name' => 'Hong Kong', 'currency_code' => 'HKD', 'currency_name' => 'HKD', 'rate' => 7.80205],
			['country_code' => 'HU', 'country_name' => 'Hungary', 'currency_code' => 'HUF', 'currency_name' => 'Forint', 'rate' => 266.5875],
			['country_code' => 'IS', 'country_name' => 'Iceland', 'currency_code' => 'ISK', 'currency_name' => 'Icelandic Krona', 'rate' => 106.04],
			['country_code' => 'IN', 'country_name' => 'India', 'currency_code' => 'INR', 'currency_name' => 'Indian Rupee', 'rate' => 64.5125],
			['country_code' => 'ID', 'country_name' => 'Indonesia', 'currency_code' => 'IDR', 'currency_name' => 'Indonesian Rupiah', 'rate' => 13538.080047],
			['country_code' => 'IR', 'country_name' => 'Iran (Islamic Republic of)', 'currency_code' => 'IRR', 'currency_name' => 'Iranian Rial', 'rate' => 34576.946723],
			['country_code' => 'IQ', 'country_name' => 'Iraq', 'currency_code' => 'IQD', 'currency_name' => 'Iraqi Dinar', 'rate' => 1165.409957],
			['country_code' => 'IE', 'country_name' => 'Ireland', 'currency_code' => 'EUR', 'currency_name' => 'Euros', 'rate' => 0.85796],
			['country_code' => 'IM', 'country_name' => 'Isle of Man', 'currency_code' => 'GBP', 'currency_name' => 'Manx pound', 'rate' => 0.752967],
			['country_code' => 'IL', 'country_name' => 'Israel', 'currency_code' => 'ILS', 'currency_name' => 'Shekel', 'rate' => 3.507045],
			['country_code' => 'IT', 'country_name' => 'Italy', 'currency_code' => 'EUR', 'currency_name' => 'Euros', 'rate' => 0.85796],
			['country_code' => 'CI', 'country_name' => 'Ivory Coast', 'currency_code' => 'XOF', 'currency_name' => 'CFA Franc BCEAO', 'rate' => 562.785111],
			['country_code' => 'JM', 'country_name' => 'Jamaica', 'currency_code' => 'JMD', 'currency_name' => 'Jamaican Dollar', 'rate' => 127.147067],
			['country_code' => 'JP', 'country_name' => 'Japan', 'currency_code' => 'JPY', 'currency_name' => 'Japanese Yen', 'rate' => 113.90083333],
			['country_code' => 'JE', 'country_name' => 'Jersey', 'currency_code' => 'GBP', 'currency_name' => 'Sterling', 'rate' => 0.752967],
			['country_code' => 'JO', 'country_name' => 'Jordan', 'currency_code' => 'JOD', 'currency_name' => 'Jordanian Dinar', 'rate' => 0.709001],
			['country_code' => 'KZ', 'country_name' => 'Kazakhstan', 'currency_code' => 'KZT', 'currency_name' => 'Tenge', 'rate' => 335.522793],
			['country_code' => 'KE', 'country_name' => 'Kenya', 'currency_code' => 'KES', 'currency_name' => 'Kenyan Shilling', 'rate' => 103.705],
			['country_code' => 'KI', 'country_name' => 'Kiribati', 'currency_code' => 'AUD', 'currency_name' => 'Australian Dollars', 'rate' => 1.295308],
			['country_code' => 'KP', 'country_name' => 'Korea North', 'currency_code' => 'KPW', 'currency_name' => 'Won', 'rate' => 900],
			['country_code' => 'KR', 'country_name' => 'Korea South', 'currency_code' => 'KRW', 'currency_name' => 'Won', 'rate' => 1113.4],
			['country_code' => 'KW', 'country_name' => 'Kuwait', 'currency_code' => 'KWD', 'currency_name' => 'Kuwaiti Dinar', 'rate' => 0.302209],
			['country_code' => 'KG', 'country_name' => 'Kyrgyzstan', 'currency_code' => 'KGS', 'currency_name' => 'Som', 'rate' => 68.735479],
			['country_code' => 'LA', 'country_name' => 'Lao PeopleÕs Democratic Republic', 'currency_code' => 'LAK', 'currency_name' => 'Kip', 'rate' => 8302.75],
			['country_code' => 'LA', 'country_name' => 'Laos', 'currency_code' => 'LAK', 'currency_name' => 'Lao kip', 'rate' => 8302.75],
			['country_code' => 'LV', 'country_name' => 'Latvia', 'currency_code' => 'LVL', 'currency_name' => 'Lat', 'rate' => NULL],
			['country_code' => 'LB', 'country_name' => 'Lebanon', 'currency_code' => 'LBP', 'currency_name' => 'Lebanese Pound', 'rate' => 1516.45],
			['country_code' => 'LS', 'country_name' => 'Lesotho', 'currency_code' => 'LSL', 'currency_name' => 'Loti', 'rate' => 14.145022],
			['country_code' => 'LR', 'country_name' => 'Liberia', 'currency_code' => 'LRD', 'currency_name' => 'Liberian Dollar', 'rate' => 119.354136],
			['country_code' => 'LY', 'country_name' => 'Libyan Arab Jamahiriya', 'currency_code' => 'LYD', 'currency_name' => 'Libyan Dinar', 'rate' => 1.368013],
			['country_code' => 'LI', 'country_name' => 'Liechtenstein', 'currency_code' => 'CHF', 'currency_name' => 'Swiss Franc', 'rate' => 0.99955],
			['country_code' => 'LT', 'country_name' => 'Lithuania', 'currency_code' => 'LTL', 'currency_name' => 'Lita', 'rate' => NULL],
			['country_code' => 'LU', 'country_name' => 'Luxembourg', 'currency_code' => 'EUR', 'currency_name' => 'Euros', 'rate' => 0.85796],
			['country_code' => 'MO', 'country_name' => 'Macao S.A.R.', 'currency_code' => 'MOP', 'currency_name' => 'Macanese pataca', 'rate' => 8.039064],
			['country_code' => 'MO', 'country_name' => 'Macau', 'currency_code' => 'MOP', 'currency_name' => 'Pataca', 'rate' => 8.039064],
			['country_code' => 'MK', 'country_name' => 'Macedonia', 'currency_code' => 'MKD', 'currency_name' => 'Denar', 'rate' => 52.835],
			['country_code' => 'MG', 'country_name' => 'Madagascar', 'currency_code' => 'MGA', 'currency_name' => 'Malagasy Franc', 'rate' => 3173.55],
			['country_code' => 'MW', 'country_name' => 'Malawi', 'currency_code' => 'MWK', 'currency_name' => 'Malawian Kwacha', 'rate' => 726.664645],
			['country_code' => 'MY', 'country_name' => 'Malaysia', 'currency_code' => 'MYR', 'currency_name' => 'Ringgit', 'rate' => 4.2275],
			['country_code' => 'MV', 'country_name' => 'Maldives', 'currency_code' => 'MVR', 'currency_name' => 'Rufiyaa', 'rate' => 15.409873],
			['country_code' => 'ML', 'country_name' => 'Mali', 'currency_code' => 'XOF', 'currency_name' => 'CFA Franc BCEAO', 'rate' => 562.785111],
			['country_code' => 'MT', 'country_name' => 'Malta', 'currency_code' => 'MTL', 'currency_name' => 'Maltese Lira', 'rate' => NULL],
			['country_code' => 'MH', 'country_name' => 'Marshall Islands', 'currency_code' => 'USD', 'currency_name' => 'USD', 'rate' => 1],
			['country_code' => 'MQ', 'country_name' => 'Martinique', 'currency_code' => 'EUR', 'currency_name' => 'Euros', 'rate' => 0.85796],
			['country_code' => 'MR', 'country_name' => 'Mauritania', 'currency_code' => 'MRO', 'currency_name' => 'Ouguiya', 'rate' => 355.302795],
			['country_code' => 'MU', 'country_name' => 'Mauritius', 'currency_code' => 'MUR', 'currency_name' => 'Mauritian Rupee', 'rate' => 34.253],
			['country_code' => 'YT', 'country_name' => 'Mayotte', 'currency_code' => 'EUR', 'currency_name' => 'Euros', 'rate' => 0.85796],
			['country_code' => 'MX', 'country_name' => 'Mexico', 'currency_code' => 'MXN', 'currency_name' => 'Peso', 'rate' => 19.0413],
			['country_code' => 'FM', 'country_name' => 'Micronesia Federated States of', 'currency_code' => 'USD', 'currency_name' => 'USD', 'rate' => 1],
			['country_code' => 'MD', 'country_name' => 'Moldova Republic of', 'currency_code' => 'MDL', 'currency_name' => 'Leu', 'rate' => 17.456],
			['country_code' => 'MC', 'country_name' => 'Monaco', 'currency_code' => 'EUR', 'currency_name' => 'Euros', 'rate' => 0.85796],
			['country_code' => 'MN', 'country_name' => 'Mongolia', 'currency_code' => 'MNT', 'currency_name' => 'Tugrik', 'rate' => 2452.599147],
			['country_code' => 'ME', 'country_name' => 'Montenegro', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'rate' => 0.85796],
			['country_code' => 'MS', 'country_name' => 'Montserrat', 'currency_code' => 'XCD', 'currency_name' => 'East Caribbean Dollar', 'rate' => 2.70255],
			['country_code' => 'MA', 'country_name' => 'Morocco', 'currency_code' => 'MAD', 'currency_name' => 'Dirham', 'rate' => 9.494341],
			['country_code' => 'MZ', 'country_name' => 'Mozambique', 'currency_code' => 'MZN', 'currency_name' => 'Metical', 'rate' => 60.904857],
			['country_code' => 'MM', 'country_name' => 'Myanmar', 'currency_code' => 'MMK', 'currency_name' => 'Kyat', 'rate' => 1354.9],
			['country_code' => 'NA', 'country_name' => 'Namibia', 'currency_code' => 'NAD', 'currency_name' => 'Dollar', 'rate' => 14.145022],
			['country_code' => 'NR', 'country_name' => 'Nauru', 'currency_code' => 'AUD', 'currency_name' => 'Australian Dollars', 'rate' => 1.295308],
			['country_code' => 'NP', 'country_name' => 'Nepal', 'currency_code' => 'NPR', 'currency_name' => 'Nepalese Rupee', 'rate' => 103.377151],
			['country_code' => 'NL', 'country_name' => 'Netherlands', 'currency_code' => 'EUR', 'currency_name' => 'Euros', 'rate' => 0.85796],
			['country_code' => 'AN', 'country_name' => 'Netherlands Antilles', 'currency_code' => 'ANG', 'currency_name' => 'Netherlands Antilles Guilder', 'rate' => 1.785544],
			['country_code' => 'NC', 'country_name' => 'New Caledonia', 'currency_code' => 'XPF', 'currency_name' => 'CFP Franc', 'rate' => 102.381906],
			['country_code' => 'NZ', 'country_name' => 'New Zealand', 'currency_code' => 'NZD', 'currency_name' => 'New Zealand Dollars', 'rate' => 1.444878],
			['country_code' => 'NI', 'country_name' => 'Nicaragua', 'currency_code' => 'NIO', 'currency_name' => 'Cordoba Oro', 'rate' => 30.784803],
			['country_code' => 'NE', 'country_name' => 'Niger', 'currency_code' => 'XOF', 'currency_name' => 'CFA Franc BCEAO', 'rate' => 562.785111],
			['country_code' => 'NG', 'country_name' => 'Nigeria', 'currency_code' => 'NGN', 'currency_name' => 'Naira', 'rate' => 359.730849],
			['country_code' => 'NU', 'country_name' => 'Niue', 'currency_code' => 'NZD', 'currency_name' => 'New Zealand Dollars', 'rate' => 1.444878],
			['country_code' => 'NF', 'country_name' => 'Norfolk Island', 'currency_code' => 'AUD', 'currency_name' => 'Australian Dollars', 'rate' => 1.295308],
			['country_code' => 'MP', 'country_name' => 'Northern Mariana Islands', 'currency_code' => 'USD', 'currency_name' => 'USD', 'rate' => 1],
			['country_code' => 'NO', 'country_name' => 'Norway', 'currency_code' => 'NOK', 'currency_name' => 'Norwegian Krone', 'rate' => 8.124565],
			['country_code' => 'OM', 'country_name' => 'Oman', 'currency_code' => 'OMR', 'currency_name' => 'Sul Rial', 'rate' => 0.384857],
			['country_code' => 'PK', 'country_name' => 'Pakistan', 'currency_code' => 'PKR', 'currency_name' => 'Rupee', 'rate' => 105.335922],
			['country_code' => 'PW', 'country_name' => 'Palau', 'currency_code' => 'USD', 'currency_name' => 'USD', 'rate' => 1],
			['country_code' => 'PS', 'country_name' => 'Palestinian Territory', 'currency_code' => 'JOD', 'currency_name' => 'Jordanian dinar', 'rate' => 0.709001],
			['country_code' => 'PA', 'country_name' => 'Panama', 'currency_code' => 'PAB', 'currency_name' => 'Balboa', 'rate' => 1],
			['country_code' => 'PG', 'country_name' => 'Papua New Guinea', 'currency_code' => 'PGK', 'currency_name' => 'Kina', 'rate' => 3.219138],
			['country_code' => 'PY', 'country_name' => 'Paraguay', 'currency_code' => 'PYG', 'currency_name' => 'Guarani', 'rate' => 5638.55],
			['country_code' => 'PE', 'country_name' => 'Peru', 'currency_code' => 'PEN', 'currency_name' => 'Nuevo Sol', 'rate' => 3.249011],
			['country_code' => 'PH', 'country_name' => 'Philippines', 'currency_code' => 'PHP', 'currency_name' => 'Peso', 'rate' => 51.48],
			['country_code' => 'PN', 'country_name' => 'Pitcairn', 'currency_code' => 'NZD', 'currency_name' => 'New Zealand Dollars', 'rate' => 1.444878],
			['country_code' => 'PL', 'country_name' => 'Poland', 'currency_code' => 'PLN', 'currency_name' => 'Zloty', 'rate' => 3.63425],
			['country_code' => 'PT', 'country_name' => 'Portugal', 'currency_code' => 'EUR', 'currency_name' => 'Euros', 'rate' => 0.85796],
			['country_code' => 'PR', 'country_name' => 'Puerto Rico', 'currency_code' => 'USD', 'currency_name' => 'USD', 'rate' => 1],
			['country_code' => 'QA', 'country_name' => 'Qatar', 'currency_code' => 'QAR', 'currency_name' => 'Rial', 'rate' => 3.806363],
			['country_code' => 'RE', 'country_name' => 'Reunion', 'currency_code' => 'EUR', 'currency_name' => 'Euros', 'rate' => 0.85796],
			['country_code' => 'RO', 'country_name' => 'Romania', 'currency_code' => 'RON', 'currency_name' => 'Leu', 'rate' => 3.948331],
			['country_code' => 'RU', 'country_name' => 'Russian Federation', 'currency_code' => 'RUB', 'currency_name' => 'Ruble', 'rate' => 58.1921],
			['country_code' => 'RW', 'country_name' => 'Rwanda', 'currency_code' => 'RWF', 'currency_name' => 'Rwanda Franc', 'rate' => 854.315],
			['country_code' => 'BL', 'country_name' => 'Saint Barthelemy', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'rate' => 0.85796],
			['country_code' => 'SH', 'country_name' => 'Saint Helena', 'currency_code' => 'GBP', 'currency_name' => 'Saint Helena pound', 'rate' => 0.752967],
			['country_code' => 'KN', 'country_name' => 'Saint Kitts', 'currency_code' => 'XCD', 'currency_name' => 'East Caribbean Dollar', 'rate' => 2.70255],
			['country_code' => 'LC', 'country_name' => 'Saint Lucia', 'currency_code' => 'XCD', 'currency_name' => 'East Caribbean Dollar', 'rate' => 2.70255],
			['country_code' => 'MF', 'country_name' => 'Saint Martin (French part)', 'currency_code' => 'ANG', 'currency_name' => 'Netherlands Antillean guilder', 'rate' => 1.785544],
			['country_code' => 'PM', 'country_name' => 'Saint Pierre and Miquelon', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'rate' => 0.85796],
			['country_code' => 'VC', 'country_name' => 'Saint Vincent Grenadines', 'currency_code' => 'XCD', 'currency_name' => 'East Caribbean Dollar', 'rate' => 2.70255],
			['country_code' => 'WS', 'country_name' => 'Samoa', 'currency_code' => 'EUR', 'currency_name' => 'Euros', 'rate' => 0.85796],
			['country_code' => 'SM', 'country_name' => 'San Marino', 'currency_code' => 'EUR', 'currency_name' => 'Euros', 'rate' => 0.85796],
			['country_code' => 'ST', 'country_name' => 'Sao Tome and Principe', 'currency_code' => 'STD', 'currency_name' => 'Dobra', 'rate' => 20907.099895],
			['country_code' => 'SA', 'country_name' => 'Saudi Arabia', 'currency_code' => 'SAR', 'currency_name' => 'Riyal', 'rate' => 3.75],
			['country_code' => 'SN', 'country_name' => 'Senegal', 'currency_code' => 'XOF', 'currency_name' => 'CFA Franc BCEAO', 'rate' => 562.785111],
			['country_code' => 'RS', 'country_name' => 'Serbia', 'currency_code' => 'RSD', 'currency_name' => 'Serbian dinar', 'rate' => 102.02],
			['country_code' => 'SC', 'country_name' => 'Seychelles', 'currency_code' => 'SCR', 'currency_name' => 'Rupee', 'rate' => 13.90416],
			['country_code' => 'SL', 'country_name' => 'Sierra Leone', 'currency_code' => 'SLL', 'currency_name' => 'Leone', 'rate' => 7643.328121],
			['country_code' => 'SG', 'country_name' => 'Singapore', 'currency_code' => 'SGD', 'currency_name' => 'Dollar', 'rate' => 1.358696],
			['country_code' => 'SK', 'country_name' => 'Slovakia (Slovak Republic)', 'currency_code' => 'SKK', 'currency_name' => 'Koruna', 'rate' => NULL],
			['country_code' => 'SI', 'country_name' => 'Slovenia', 'currency_code' => 'EUR', 'currency_name' => 'Euros', 'rate' => 0.85796],
			['country_code' => 'SB', 'country_name' => 'Solomon Islands', 'currency_code' => 'SBD', 'currency_name' => 'Solomon Islands Dollar', 'rate' => 7.800511],
			['country_code' => 'SO', 'country_name' => 'Somalia', 'currency_code' => 'SOS', 'currency_name' => 'Shilling', 'rate' => 578.561731],
			['country_code' => 'ZA', 'country_name' => 'South Africa', 'currency_code' => 'ZAR', 'currency_name' => 'Rand', 'rate' => 13.935413],
			['country_code' => 'GS', 'country_name' => 'South Georgia and the South Sandwich Islands', 'currency_code' => 'GBP', 'currency_name' => 'Sterling', 'rate' => 0.752967],
			['country_code' => 'ES', 'country_name' => 'Spain', 'currency_code' => 'EUR', 'currency_name' => 'Euros', 'rate' => 0.85796],
			['country_code' => 'LK', 'country_name' => 'Sri Lanka', 'currency_code' => 'LKR', 'currency_name' => 'Rupee', 'rate' => 153.767344],
			['country_code' => 'SD', 'country_name' => 'Sudan', 'currency_code' => 'SDG', 'currency_name' => 'Dinar', 'rate' => 6.678746],
			['country_code' => 'SR', 'country_name' => 'Suriname', 'currency_code' => 'SRD', 'currency_name' => 'Surinamese Guilder', 'rate' => 7.448],
			['country_code' => 'SJ', 'country_name' => 'Svalbard and Jan Mayen Islands', 'currency_code' => 'NOK', 'currency_name' => 'Norwegian Krone', 'rate' => 8.124565],
			['country_code' => 'SZ', 'country_name' => 'Swaziland', 'currency_code' => 'SZL', 'currency_name' => 'Lilangeni', 'rate' => 14.142681],
			['country_code' => 'SE', 'country_name' => 'Sweden', 'currency_code' => 'SEK', 'currency_name' => 'Krona', 'rate' => 8.37902],
			['country_code' => 'CH', 'country_name' => 'Switzerland', 'currency_code' => 'CHF', 'currency_name' => 'Swiss Franc', 'rate' => 0.99955],
			['country_code' => 'SY', 'country_name' => 'Syrian Arab Republic', 'currency_code' => 'SYP', 'currency_name' => 'Syrian Pound', 'rate' => 514.98999],
			['country_code' => 'TW', 'country_name' => 'Taiwan', 'currency_code' => 'TWD', 'currency_name' => 'Dollar', 'rate' => 30.1905],
			['country_code' => 'TJ', 'country_name' => 'Tajikistan', 'currency_code' => 'TJS', 'currency_name' => 'Tajikistan Ruble', 'rate' => 8.81295],
			['country_code' => 'TZ', 'country_name' => 'Tanzania', 'currency_code' => 'TZS', 'currency_name' => 'Shilling', 'rate' => 2248.9],
			['country_code' => 'TH', 'country_name' => 'Thailand', 'currency_code' => 'THB', 'currency_name' => 'Baht', 'rate' => 33.1072],
			['country_code' => 'TG', 'country_name' => 'Togo', 'currency_code' => 'XOF', 'currency_name' => 'CFA Franc BCEAO', 'rate' => 562.785111],
			['country_code' => 'TK', 'country_name' => 'Tokelau', 'currency_code' => 'NZD', 'currency_name' => 'New Zealand Dollars', 'rate' => 1.444878],
			['country_code' => 'TO', 'country_name' => 'Tonga', 'currency_code' => 'TOP', 'currency_name' => 'PaÕanga', 'rate' => 2.257082],
			['country_code' => 'TT', 'country_name' => 'Trinidad and Tobago', 'currency_code' => 'TTD', 'currency_name' => 'Trinidad and Tobago Dollar', 'rate' => 6.732185],
			['country_code' => 'TN', 'country_name' => 'Tunisia', 'currency_code' => 'TND', 'currency_name' => 'Tunisian Dinar', 'rate' => 2.517],
			['country_code' => 'TR', 'country_name' => 'Turkey', 'currency_code' => 'TRY', 'currency_name' => 'Lira', 'rate' => 3.802034],
			['country_code' => 'TM', 'country_name' => 'Turkmenistan', 'currency_code' => 'TMT', 'currency_name' => 'Manat', 'rate' => 3.499986],
			['country_code' => 'TC', 'country_name' => 'Turks and Caicos Islands', 'currency_code' => 'USD', 'currency_name' => 'USD', 'rate' => 1],
			['country_code' => 'TV', 'country_name' => 'Tuvalu', 'currency_code' => 'AUD', 'currency_name' => 'Australian Dollars', 'rate' => 1.295308],
			['country_code' => 'UG', 'country_name' => 'Uganda', 'currency_code' => 'UGX', 'currency_name' => 'Shilling', 'rate' => 3653.2],
			['country_code' => 'UA', 'country_name' => 'Ukraine', 'currency_code' => 'UAH', 'currency_name' => 'Hryvnia', 'rate' => 26.888392],
			['country_code' => 'AE', 'country_name' => 'United Arab Emirates', 'currency_code' => 'AED', 'currency_name' => 'Dirham', 'rate' => 3.673014],
			['country_code' => 'GB', 'country_name' => 'United Kingdom', 'currency_code' => 'GBP', 'currency_name' => 'Sterling', 'rate' => 0.752967],
			['country_code' => 'US', 'country_name' => 'United States', 'currency_code' => 'USD', 'currency_name' => 'USD', 'rate' => 1],
			['country_code' => 'UM', 'country_name' => 'United States Minor Outlying Islands', 'currency_code' => 'USD', 'currency_name' => 'USD', 'rate' => 1],
			['country_code' => 'UY', 'country_name' => 'Uruguay', 'currency_code' => 'UYU', 'currency_name' => 'Peso', 'rate' => 29.175769],
			['country_code' => 'USAF', 'country_name' => 'US Armed Forces', 'currency_code' => 'USD', 'currency_name' => 'US Dollar', 'rate' => 1],
			['country_code' => 'UZ', 'country_name' => 'Uzbekistan', 'currency_code' => 'UZS', 'currency_name' => 'Som', 'rate' => 8080.75],
			['country_code' => 'VU', 'country_name' => 'Vanuatu', 'currency_code' => 'VUV', 'currency_name' => 'Vatu', 'rate' => 105.939999],
			['country_code' => 'VA', 'country_name' => 'Vatican City State (Holy See)', 'currency_code' => 'EUR', 'currency_name' => 'Euros', 'rate' => 0.85796],
			['country_code' => 'VE', 'country_name' => 'Venezuela', 'currency_code' => 'VEF', 'currency_name' => 'Bolivar', 'rate' => 10.78085],
			['country_code' => 'VN', 'country_name' => 'Vietnam', 'currency_code' => 'VND', 'currency_name' => 'Dong', 'rate' => 22717.553308],
			['country_code' => 'VG', 'country_name' => 'Virgin Islands (British)', 'currency_code' => 'USD', 'currency_name' => 'USD', 'rate' => 1],
			['country_code' => 'VI', 'country_name' => 'Virgin Islands (US)', 'currency_code' => 'USD', 'currency_name' => 'USD', 'rate' => 1],
			['country_code' => 'WF', 'country_name' => 'Wallis and Futuna Islands', 'currency_code' => 'XPF', 'currency_name' => 'CFP Franc', 'rate' => 102.381906],
			['country_code' => 'EH', 'country_name' => 'Western Sahara', 'currency_code' => 'MAD', 'currency_name' => 'Dirham', 'rate' => 9.494341],
			['country_code' => 'YE', 'country_name' => 'Yemen', 'currency_code' => 'YER', 'currency_name' => 'Rial', 'rate' => 250.306642],
			['country_code' => 'ZM', 'country_name' => 'Zambia', 'currency_code' => 'ZMK', 'currency_name' => 'Kwacha', 'rate' => NULL],
			['country_code' => 'ZW', 'country_name' => 'Zimbabwe', 'currency_code' => 'ZWD', 'currency_name' => 'Zimbabwe Dollar', 'rate' => NULL],			
          ];
          foreach ($data as $bind) {
              $setup->getConnection()
                ->insertForce($setup->getTable('fgc_currencies'), $bind);
          }
    }
}
