<?php
namespace FGC\CurrencyExchange\Setup;

use Magento\Framework\Setup\InstallDataInterface;
use Magento\Framework\Setup\ModuleContextInterface;
use Magento\Framework\Setup\ModuleDataSetupInterface;

/**
 * @codeCoverageIgnore
 */
class InstallData implements InstallDataInterface {
    /**
     * {@inheritdoc}
     * @SuppressWarnings(PHPMD.CyclomaticComplexity)
     * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
     * @SuppressWarnings(PHPMD.NPathComplexity)
     */
    public function install(ModuleDataSetupInterface $setup, ModuleContextInterface $context) {
		/**
        * Install data currency rate
        */
        $data = [
			  ['country_code' => 'AED', 'currency_rate' => 3.672896				],
			  ['country_code' => 'AFN', 'currency_rate' => 68.351494			],
			  ['country_code' => 'ALL', 'currency_rate' => 114.83				],
			  ['country_code' => 'AMD', 'currency_rate' => 482.685				],
			  ['country_code' => 'ANG', 'currency_rate' => 1.784437				],
			  ['country_code' => 'AOA', 'currency_rate' => 165.9225				],
			  ['country_code' => 'ARS', 'currency_rate' => 17.636				],
			  ['country_code' => 'AUD', 'currency_rate' => 1.304018				],
			  ['country_code' => 'AWG', 'currency_rate' => 1.790501				],
			  ['country_code' => 'AZN', 'currency_rate' => 1.6985				],
			  ['country_code' => 'BAM', 'currency_rate' => 1.679998				],
			  ['country_code' => 'BBD', 'currency_rate' => 2					],
			  ['country_code' => 'BDT', 'currency_rate' => 83.150915			],
			  ['country_code' => 'BGN', 'currency_rate' => 1.68205				],
			  ['country_code' => 'BHD', 'currency_rate' => 0.377085				],
			  ['country_code' => 'BIF', 'currency_rate' => 1755					],
			  ['country_code' => 'BMD', 'currency_rate' => 1					],
			  ['country_code' => 'BND', 'currency_rate' => 1.36071				],
			  ['country_code' => 'BOB', 'currency_rate' => 6.922785				],
			  ['country_code' => 'BRL', 'currency_rate' => 3.284294				],
			  ['country_code' => 'BSD', 'currency_rate' => 1					],
			  ['country_code' => 'BTC', 'currency_rate' => 0.000153498434		],
			  ['country_code' => 'BTN', 'currency_rate' => 64.780658			],
			  ['country_code' => 'BWP', 'currency_rate' => 10.550519			],
			  ['country_code' => 'BYN', 'currency_rate' => 1.974095				],
			  ['country_code' => 'BZD', 'currency_rate' => 2.009372				],
			  ['country_code' => 'CAD', 'currency_rate' => 1.290265				],
			  ['country_code' => 'CDF', 'currency_rate' => 1576					],
			  ['country_code' => 'CHF', 'currency_rate' => 1.002167				],
			  ['country_code' => 'CLF', 'currency_rate' => 0.02363				],
			  ['country_code' => 'CLP', 'currency_rate' => 635.75				],
			  ['country_code' => 'CNH', 'currency_rate' => 6.613988				],
			  ['country_code' => 'CNY', 'currency_rate' => 6.6123				],
			  ['country_code' => 'COP', 'currency_rate' => 3040.52				],
			  ['country_code' => 'CRC', 'currency_rate' => 569.565				],
			  ['country_code' => 'CUC', 'currency_rate' => 1					],
			  ['country_code' => 'CUP', 'currency_rate' => 25.5					],
			  ['country_code' => 'CVE', 'currency_rate' => 95.1					],
			  ['country_code' => 'CZK', 'currency_rate' => 21.99935				],
			  ['country_code' => 'DJF', 'currency_rate' => 178.97				],
			  ['country_code' => 'DKK', 'currency_rate' => 6.405335				],
			  ['country_code' => 'DOP', 'currency_rate' => 47.855				],
			  ['country_code' => 'DZD', 'currency_rate' => 115.186				],
			  ['country_code' => 'EGP', 'currency_rate' => 17.6251				],
			  ['country_code' => 'ERN', 'currency_rate' => 15.341062			],
			  ['country_code' => 'ETB', 'currency_rate' => 27.2695				],
			  ['country_code' => 'EUR', 'currency_rate' => 0.860805				],
			  ['country_code' => 'FJD', 'currency_rate' => 2.079494				],
			  ['country_code' => 'FKP', 'currency_rate' => 0.752123				],
			  ['country_code' => 'GBP', 'currency_rate' => 0.752123				],
			  ['country_code' => 'GEL', 'currency_rate' => 2.544054				],
			  ['country_code' => 'GGP', 'currency_rate' => 0.752123				],
			  ['country_code' => 'GHS', 'currency_rate' => 4.4					],
			  ['country_code' => 'GIP', 'currency_rate' => 0.752123				],
			  ['country_code' => 'GMD', 'currency_rate' => 47.45				],
			  ['country_code' => 'GNF', 'currency_rate' => 9000					],
			  ['country_code' => 'GTQ', 'currency_rate' => 7.350207				],
			  ['country_code' => 'GYD', 'currency_rate' => 207.725				],
			  ['country_code' => 'HKD', 'currency_rate' => 7.80195				],
			  ['country_code' => 'HNL', 'currency_rate' => 23.61624				],
			  ['country_code' => 'HRK', 'currency_rate' => 6.474106				],
			  ['country_code' => 'HTG', 'currency_rate' => 63.344213			],
			  ['country_code' => 'HUF', 'currency_rate' => 268.268333			],
			  ['country_code' => 'IDR', 'currency_rate' => 13552.080047			],
			  ['country_code' => 'ILS', 'currency_rate' => 3.513253				],
			  ['country_code' => 'IMP', 'currency_rate' => 0.752123				],
			  ['country_code' => 'INR', 'currency_rate' => 64.6065				],
			  ['country_code' => 'IQD', 'currency_rate' => 1183.5				],
			  ['country_code' => 'IRR', 'currency_rate' => 34576.946723			],
			  ['country_code' => 'ISK', 'currency_rate' => 106.115771			],
			  ['country_code' => 'JEP', 'currency_rate' => 0.752123				],
			  ['country_code' => 'JMD', 'currency_rate' => 127.026305			],
			  ['country_code' => 'JOD', 'currency_rate' => 0.708901				],
			  ['country_code' => 'JPY', 'currency_rate' => 114.17866667			],
			  ['country_code' => 'KES', 'currency_rate' => 103.808333			],
			  ['country_code' => 'KGS', 'currency_rate' => 68.735479			],
			  ['country_code' => 'KHR', 'currency_rate' => 4040					],
			  ['country_code' => 'KMF', 'currency_rate' => 423.75				],
			  ['country_code' => 'KPW', 'currency_rate' => 900					],
			  ['country_code' => 'KRW', 'currency_rate' => 1112.4125			],
			  ['country_code' => 'KWD', 'currency_rate' => 0.302625				],
			  ['country_code' => 'KYD', 'currency_rate' => 0.833029				],
			  ['country_code' => 'KZT', 'currency_rate' => 335.25				],
			  ['country_code' => 'LAK', 'currency_rate' => 8322					],
			  ['country_code' => 'LBP', 'currency_rate' => 1510					],
			  ['country_code' => 'LKR', 'currency_rate' => 153.65				],
			  ['country_code' => 'LRD', 'currency_rate' => 119.375				],
			  ['country_code' => 'LSL', 'currency_rate' => 14.135				],
			  ['country_code' => 'LYD', 'currency_rate' => 1.38					],
			  ['country_code' => 'MAD', 'currency_rate' => 9.50765				],
			  ['country_code' => 'MDL', 'currency_rate' => 17.400472			],
			  ['country_code' => 'MGA', 'currency_rate' => 3165					],
			  ['country_code' => 'MKD', 'currency_rate' => 52.9905				],
			  ['country_code' => 'MMK', 'currency_rate' => 1352.849087			],
			  ['country_code' => 'MNT', 'currency_rate' => 2452.925814			],
			  ['country_code' => 'MOP', 'currency_rate' => 8.033905				],
			  ['country_code' => 'MRO', 'currency_rate' => 355.5				],
			  ['country_code' => 'MUR', 'currency_rate' => 34.249				],
			  ['country_code' => 'MVR', 'currency_rate' => 15.400126			],
			  ['country_code' => 'MWK', 'currency_rate' => 726.1				],
			  ['country_code' => 'MXN', 'currency_rate' => 19.182909			],
			  ['country_code' => 'MYR', 'currency_rate' => 4.2297				],
			  ['country_code' => 'MZN', 'currency_rate' => 60.994761			],
			  ['country_code' => 'NAD', 'currency_rate' => 14.135				],
			  ['country_code' => 'NGN', 'currency_rate' => 359					],
			  ['country_code' => 'NIO', 'currency_rate' => 30.765661			],
			  ['country_code' => 'NOK', 'currency_rate' => 8.14909				],
			  ['country_code' => 'NPR', 'currency_rate' => 103.318699			],
			  ['country_code' => 'NZD', 'currency_rate' => 1.451424				],
			  ['country_code' => 'OMR', 'currency_rate' => 0.38502				],
			  ['country_code' => 'PAB', 'currency_rate' => 1					],
			  ['country_code' => 'PEN', 'currency_rate' => 3.249678				],
			  ['country_code' => 'PGK', 'currency_rate' => 3.217004				],
			  ['country_code' => 'PHP', 'currency_rate' => 51.658				],
			  ['country_code' => 'PKR', 'currency_rate' => 105.2				],
			  ['country_code' => 'PLN', 'currency_rate' => 3.6427				],
			  ['country_code' => 'PYG', 'currency_rate' => 5634.95				],
			  ['country_code' => 'QAR', 'currency_rate' => 3.829988				],
			  ['country_code' => 'RON', 'currency_rate' => 3.962643				],
			  ['country_code' => 'RSD', 'currency_rate' => 102.464708			],
			  ['country_code' => 'RUB', 'currency_rate' => 58.1973				],
			  ['country_code' => 'RWF', 'currency_rate' => 840					],
			  ['country_code' => 'SAR', 'currency_rate' => 3.75095				],
			  ['country_code' => 'SBD', 'currency_rate' => 7.808111				],
			  ['country_code' => 'SCR', 'currency_rate' => 13.410546			],
			  ['country_code' => 'SDG', 'currency_rate' => 6.685				],
			  ['country_code' => 'SEK', 'currency_rate' => 8.39832				],
			  ['country_code' => 'SGD', 'currency_rate' => 1.361409				],
			  ['country_code' => 'SHP', 'currency_rate' => 0.752123				],
			  ['country_code' => 'SLL', 'currency_rate' => 7643.328121			],
			  ['country_code' => 'SOS', 'currency_rate' => 592					],
			  ['country_code' => 'SRD', 'currency_rate' => 7.448				],
			  ['country_code' => 'SSP', 'currency_rate' => 130.2634				],
			  ['country_code' => 'STD', 'currency_rate' => 20923.349895			],
			  ['country_code' => 'SVC', 'currency_rate' => 8.746873				],
			  ['country_code' => 'SYP', 'currency_rate' => 514.98999			],
			  ['country_code' => 'SZL', 'currency_rate' => 14.133933			],
			  ['country_code' => 'THB', 'currency_rate' => 33.163				],
			  ['country_code' => 'TJS', 'currency_rate' => 8.807234				],
			  ['country_code' => 'TMT', 'currency_rate' => 3.50998				],
			  ['country_code' => 'TND', 'currency_rate' => 2.496338				],
			  ['country_code' => 'TOP', 'currency_rate' => 2.271282				],
			  ['country_code' => 'TRY', 'currency_rate' => 3.827195				],
			  ['country_code' => 'TTD', 'currency_rate' => 6.727862				],
			  ['country_code' => 'TWD', 'currency_rate' => 30.160685			],
			  ['country_code' => 'TZS', 'currency_rate' => 2248.3				],
			  ['country_code' => 'UAH', 'currency_rate' => 26.873331			],
			  ['country_code' => 'UGX', 'currency_rate' => 3650.85				],
			  ['country_code' => 'USD', 'currency_rate' => 1					],
			  ['country_code' => 'UYU', 'currency_rate' => 29.184286			],
			  ['country_code' => 'UZS', 'currency_rate' => 8074.35				],
			  ['country_code' => 'VEF', 'currency_rate' => 10.720909			],
			  ['country_code' => 'VND', 'currency_rate' => 22717.953308			],
			  ['country_code' => 'VUV', 'currency_rate' => 106.52				],
			  ['country_code' => 'WST', 'currency_rate' => 2.546507				],
			  ['country_code' => 'XAF', 'currency_rate' => 564.651053			],
			  ['country_code' => 'XAG', 'currency_rate' => 0.05905811			],
			  ['country_code' => 'XAU', 'currency_rate' => 0.00078428			],
			  ['country_code' => 'XCD', 'currency_rate' => 2.70255				],
			  ['country_code' => 'XDR', 'currency_rate' => 0.711903				],
			  ['country_code' => 'XOF', 'currency_rate' => 564.651053			],
			  ['country_code' => 'XPD', 'currency_rate' => 0.00100353			],
			  ['country_code' => 'XPF', 'currency_rate' => 102.721358			],
			  ['country_code' => 'XPT', 'currency_rate' => 0.00107528			],
			  ['country_code' => 'YER', 'currency_rate' => 250.281642			],
			  ['country_code' => 'ZAR', 'currency_rate' => 14.13074				],
			  ['country_code' => 'ZMW', 'currency_rate' => 10.021814			],
			  ['country_code' => 'ZWL', 'currency_rate' => 322.355011			]
          ];
          foreach ($data as $bind) {
              $setup->getConnection()
                ->insertForce($setup->getTable('fgc_currencies'), $bind);
          }
    }
}
